version: '2'

services:
  elasticsearch:
    # image: 'bitnami/elasticsearch:${ELASTIC_VERSION}'
    # ports:
    #   - '9200:9200'
    #   - '9300:9300'
    # volumes:
    #   - 'elasticsearch_data:/bitnami/elasticsearch/data-v7'

    image: 'docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}'
    # container_name: lixibox_elasticsearch
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - '9200:9200'
      - '9300:9300'
    restart: always

# volumes:
#   elasticsearch_data:
#     driver: local
#
