version: '2'

services:
  elasticsearch:
    image: 'bitnami/elasticsearch:${ELASTIC_VERSION}'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
