version: '2'

services:
  lixibox_redis:
    image: 'redis:${VERSION}'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes
    restart: always

volumes:
  redis_data:
